# Generated by Django 4.0.5 on 2022-10-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('drink', models.TextField()),
                ('milk', models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')])),
                ('temperature', models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')])),
                ('decaf', models.BooleanField(default=False)),
                ('strength', models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')])),
                ('sugar', models.IntegerField()),
            ],
        ),
    ]
