# Generated by Django 4.0.5 on 2022-10-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='decaf',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='milk',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='strength',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='temperature',
            field=models.TextField(),
        ),
    ]
