# Generated by Django 4.0.5 on 2022-10-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_order_completed_alter_order_decaf_alter_order_milk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='asd'),
            preserve_default=False,
        ),
    ]
